spring.application.name=inven-track-api
spring.datasource.url=jdbc:h2:mem:inventrack
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true